# Generated by Django 4.2.4 on 2023-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emro_boarding_house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarder',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
